### ISSUE TITLE
Get Default BrandingTheme

### ISSUE THREAD

**Issue by seankelly001** [auth0/go-auth0#110]
### Describe the problem you'd like to have solved

Add support for getting default branding theme i.e. by using this API:
https://auth0.com/docs/api/management/v2#!/Branding/get_default_branding_theme

This would be useful if current theme ID is not known

### Describe the ideal solution

A way to get the default branding theme, something like this:
```
var m &management.Management
defaultTheme, err := m.BrandingTheme.Default()
```
### Alternatives and current workarounds

Can currently get default theme like this:
```
var m &management.Management
theme := &management.BrandingTheme{}
err := m.Request(http.MethodGet, m.URI("branding", "themes", "default"), &theme)
```
### Additional context
None

**Comment by sergiught** [comment]
This is now available in the latest release https://github.com/auth0/go-auth0/releases/tag/v0.12.0 as such we'll be closing this down 🥳
