### ISSUE TITLE
Support http schema for mocking the api

### ISSUE THREAD

**Issue by AudriusDai** [auth0/go-auth0#124]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The same suggestion was already added to auth0-js lib. https://github.com/auth0/auth0.js/pull/1144

### Describe the ideal solution

https://github.com/auth0/auth0.js/pull/1144

**Comment by AudriusDai** [comment]
Ok, found one potential way: `management.WithInsecure()`. Just need to adjust the code accordingly:
`management.New(domain, management.WithClientCredentials(id, secret), management.WithInsecure())`

**Comment by sergiught** [comment]
Hey @AudriusDai as you point you there is a way to use http instead of https by calling the `WithInsecure` option for testing. We'll be closing this down.
