### ISSUE TITLE
The payload passed from ImportUsers is json encoded by Management.NewRequest and the request fails

### ISSUE THREAD

**Issue by enokids** [auth0/go-auth0#134]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The problem is happening with m.NewRequest in management.Request that ImportUsers is using at request time.
ImportUsers throws a request expecting multipart/form-data, but in m.NewRequest it does not work as expected and re-encodes the payload already completed in ImportUsers just like a normal json request. The request is then re-encoded like a normal json request.

This results in an empty body and failure.

### Expectation

That a user is created in the connection specified by auth0 using ImportUsers().

### Reproduction

```
func main() {
	m, _ := management.New(DOMAIN, management.WithClientCredentials(CLIENTID, CLIENTSECRET))

	user := map[string]interface{}{
		"email":          auth0.String(EMAIL),
		"password_hash":  auth0.String(HASH),
	}

	job := management.Job{
		ConnectionID:        auth0.String(CONNECTIONID),
		Upsert:              auth0.Bool(false),
		SendCompletionEmail: auth0.Bool(true),
		Users:               []map[string]interface{}{user},
	}
	
	_ = m.Job.ImportUsers(&job)
}
```

### Auth0 Go SDK version

v0.13.0

**Comment by sergiught** [comment]
Hey @enokids 👋🏻 

Thanks a lot for reporting this! I'll take a stab at fixing this today.

**Comment by sergiught** [comment]
This is now fixed within https://github.com/auth0/go-auth0/releases/tag/v0.14.0. Closing this down now.
