### ISSUE TITLE
Add feature to make query params a list

### ISSUE THREAD

**Issue by vandyliu** [auth0/go-auth0#135]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am trying to run Connection.List with multiple strategies, however I cannot make it like the curl request similar to `strategy=&strategy=&strategy=` because Connection.List does use the search_engine query builder and `Parameter` function replaces the strategy each time I put one

### Describe the ideal solution

Ideally a function like 
```
func ParameterArray(key, values []string) RequestOption {
	return newRequestOption(func(r *http.Request) {
		q := r.URL.Query()
                for _, value := range values {
		      q.Add(key, value)
		}
		r.URL.RawQuery = q.Encode()
	})
}
```
or something similar

### Alternatives and current workarounds

call the function 3 times

**Comment by vandyliu** [comment]
found out you can just do
```
Connection.List(
  management.Parameter("strategy[0]", "strat1"),
  management.Parameter("strategy[1]", "strat2"),
)
```

**Comment by sergiught** [comment]
That's awesome, great that you were able to find that out @vandyliu and that you shared the findings with everyone else!  🙌🏻
