### ISSUE TITLE
Add support for segment log stream

### ISSUE THREAD

**Issue by pablogamboa** [auth0/go-auth0#147]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Segment is supported at the api level but not on go-auth0 (thus not supported on terraform-provider-auth0 either!)

### Describe the ideal solution

go-auth0 and terraform-provider-auth0 support segment log streams

**Comment by sergiught** [comment]
Hey @pablogamboa 👋🏻 Support for Segment log streams was introduced in https://github.com/auth0/go-auth0/releases/tag/v0.15.0.

**Comment by pablogamboa** [comment]
@sergiught amazing thank you!
