### ISSUE TITLE
CloudQuery source plugin?

### ISSUE THREAD

**Issue by yevgenypats** [auth0/go-auth0#149]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in an Auth0 plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Auth0 data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

### Describe the ideal solution

-

**Comment by sergiught** [comment]
Hey @yevgenypats 👋🏻 

Thanks for opening an issue. The ask is definitely sensible, however this is not exactly the right place for this. 

If you go to https://marketplace.auth0.com/, at the bottom of the page there is a "Request Integration" button: 

![image](https://user-images.githubusercontent.com/28300158/213398756-283dc2e5-2333-4ecf-a128-35ba2f9647d6.png)

That will take you to https://community.auth0.com/c/marketplace/request-integration/89 where you can formalize a proposal with the appropriate team. 

Hope this helps! Looking forward to adding support for this within the Go SDK when time comes 👍🏻  

Let me know if you have any other questions.
