### ISSUE TITLE
Management client fails to fetch access token

### ISSUE THREAD

**Issue by balajis-tg** [auth0/go-auth0#150]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I’m using Auth0 GO SDK to perform some user management calls like create or update user. I can instantiate management client without any issues.

```
options := management.WithClientCredentialsAndAudience("client_id", "client_sec", "aud")
m, err := management.New("domain_url", options)
if err != nil {
	log.Error().Msgf("failed to initialize Auth0 client: %s", err.Error())
	return nil, err
}
```

But when I try to use to make some API calls (like create user for instance), it returns the following error:

```
user := &management.User{
		Email:        &req.Email,
....
	}
err := m.User.Create(user)
```

```Error message: failed to send the request: Post \"https://domain-url/api/v2/users\": oauth2: cannot fetch token: 404 Not Found\nResponse: Not found., Http status code: 500```

I can create access token and create user using cli so there is no issue with Auth0 configuration.

### Expectation

Backend server should be able to create Auth0 user using management API client.

### Reproduction

See desc

### Auth0 Go SDK version

v0.14.0

**Comment by balajis-tg** [comment]
It was a config issue. SDK works as expected.

**Comment by OGreeni** [comment]
Just faced this error too. Why doesn't `management.New()` error when authorization fails?

**Comment by qhenkart** [comment]
@balajis-tg what was the config issue?
