### ISSUE TITLE
Support for Authentication APIs

### ISSUE THREAD

**Issue by emfloyd2** [auth0/go-auth0#193]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello. I'm a long time user of the Python SDK

I started tinkering with the Go implementation, and realized it doesn't have support for the Authentication APIs.

Are there any plans to add Authentication APIs? And if so... what's the timeline for their availability?

### Describe the ideal solution

Equivalent support for what's offered in Python's `auth0.authentication` package

### Alternatives and current workarounds

Rolling our own implementation for these in Go (less than ideal), or sticking with our Python implementation

**Comment by ewanharris** [comment]
Thanks for the issue @emfloyd2!

We're looking to graduate this SDK to a v1, and one of the items we would like to tackle with this is adding an Authentication Client to align with other SDKs. I don't have any hard dates for this but we're starting work on some breaking changes for v1 soon and would then look to being the Authentication Client work.

To help us prioritise what we implement, what are the specific APIs you would need in this SDK to allow migrating from the Python SDK?

**Comment by ewanharris** [comment]
We've released a beta for the upcoming v1 release that includes the new Authentication client. You can find the documentation [here](https://pkg.go.dev/github.com/auth0/go-auth0@v1.0.0-beta.0/authentication) and we welcome any feedback you may have on trialling it.

**Comment by ewanharris** [comment]
We've just released v1.0.0 that now contains an authentication client with `Database`, `OAuth`, and `Passwordless` support.

I'm going to close this issue out but please let us know of any feedback you have!
