### ISSUE TITLE
Support Get Organization Invitation by TicketID

### ISSUE THREAD

**Issue by marckong** [auth0/go-auth0#215]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi, I am wondering why user invitation is sent with invitation ticket id and organization id, but the API does not expose search by ticket id for invitations? By the time we have a url link, we cannot look up the invitation unless we fetch all the invitations and search by ticket id. This isn't an ideal solution.

### Describe the ideal solution

Please provide an interface that allows to search an invitation by ticket id.

### Alternatives and current workarounds

The current work around is to search manually by invitation id but this does not solve the issue when the size invitations is big as paginated.

**Comment by ewanharris** [comment]
Given that this is not supported via the API I'm going to close this issue. It might be good to submit this via the [product feedback](https://auth0.com/feedback)
