### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by vendelin8** [auth0/go-auth0#221]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like to sort Users as described here: https://auth0.com/docs/api/management/v2#!/Users/get_users

### Describe the ideal solution

Having a `func Sort(s string) RequestOption { ... }` function similar to `Query` in management/management_request.go

**Comment by vendelin8** [comment]
I got it working by adding a  `management.Parameter("sort", "email")` as an additional parameter to `User.List`. But would be awesome to have a function for that similar to `func Page(page int) RequestOption`

**Comment by ewanharris** [comment]
Hey @vendelin8 I think supporting a `Sort` request option would make sense given we have other helpers like that, happy to accept a PR if you'd be interested but otherwise we'll factor this into the v1 release we have planned

**Comment by ssudaraka** [comment]
Hi @ewanharris , I wanted to take a shot at contributing and created a fork to add a helper - https://github.com/ssudaraka/go-auth0/blob/a7c6db764bdc53d2336ed3b6eb55e16fbb99f00a/management/management_request.go#L295-L302

However, I need some guidance on how to locally test my change with the local repo. If you have some spare time, can you share some details on that? I'll make sure to add that to "How to contribute" file also. Thank you!

**Comment by ewanharris** [comment]
It's great to see the interest in making a contribution so thank you @ssudaraka!

For this test I would add something similar to the existing options like [TestOptionParameter](https://github.com/ssudaraka/go-auth0/blob/a7c6db764bdc53d2336ed3b6eb55e16fbb99f00a/management/management_test.go#L129-L142), that should then be testable using `make test` (no need for any configuring of a .env file). There's some instructions on running the tests in the [contributing document](https://github.com/auth0/go-auth0/blob/main/CONTRIBUTING.md#running-the-tests) but please feel free to edit them if there's some more information that would be helpful
