### ISSUE TITLE
Add `decryptionKey` to management.ConnectionOptionsSAML

### ISSUE THREAD

**Issue by vandyliu** [auth0/go-auth0#223]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

ConnectionOptionsSAML should have `decryptionKey`. It is used in the documentation here: https://auth0.com/docs/authenticate/protocols/saml/saml-sso-integrations/sign-and-encrypt-saml-requests#use-your-key-pair-to-decrypt-encrypted-responses

### Describe the ideal solution

A new field in ConnectionOptionsSAML, where when we do a Read request for a SAML connection, that field will be filled

**Comment by ewanharris** [comment]
Thanks for the requests @vandyliu, we're focused on some work for the upcoming v1 beta currently but I'll make sure we address this in future

**Comment by vandyliu** [comment]
hey @ewanharris 
do you have an approximate timeline? also was wondering if i should just try to make a pr for this fix.
thanks!

**Comment by ewanharris** [comment]
Apologies for the delay in response here @vandyliu, I don't have a timeline right now. We'd be more than happy to accept a PR if you are interested.

**Comment by ewanharris** [comment]
Closing as this change has now been release in v1.0.0
