### ISSUE TITLE
SDK overwrites transport when sending in custom http client with WithClient()

### ISSUE THREAD

**Issue by marilangaas** [auth0/go-auth0#26]
### Describe the problem

We want to use our custom HTTP client with the management client. We are using [datadog http tracing](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http) to trace our http requests, which works by modifying the client's transport to augment it with tracing. However, it seems like our transport/roundtripper is overwritten by the "default" roundtripper in the package and the tracing does not work. When commenting out the `WithUserAgent` and `WithRateLimit` in `management.New()`, we get the desired `Transport` with tracing. 

### What was the expected behavior?

The calls to auth0 management API should function as normal and traces should appear in DataDog. 

### Reproduction

[Here](https://github.com/marilangaas/dd-go-auth0-example) is a repo that replicates a simple version of our setup, that can be used to demonstrate the issue.

Here are the values that we see for `Transport` inside our `New` function when debugging:
Before calling management.New()
```
Transport = {net/http.RoundTripper | *gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http.roundTripper}
```

After calling management.New()
```
http = {@net/http.Client}
     Transport = {net/http.RoundTripper | *github.com/PuerkitoBio/rehttp.Transport}
```

### Environment
go-auth0 v0.5.0
Go 1.17

- Datadog http tracing v1.36.0: https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http

**Comment by sergiughf** [comment]
Hey @marilangaas thanks for reporting this and really great work on creating that reproducible repo for us. It helps immensely 🙇🏻 . Our team will look into this.

**Comment by sergiughf** [comment]
As such I'll be closing this issue down as I wasn't able to reproduce. If new information arises please reply to this and we can take another look 🙏🏻
