### ISSUE TITLE
Cannot remove the User Picture

### ISSUE THREAD

**Issue by JakubC-projects** [auth0/go-auth0#272]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

It seems to not be possible to remove the profile picture of a user even though the auth0 management API allows it

Here is the auth0 request that I'd like to make using the SDK
```sh
curl -L -X PATCH 'https://AUTH0_DOMAIN/api/v2/users/USER_ID' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer 🔒' \
-d '{"picture":null}'
```

But a request like that is impossible to make becuase in the SDK, the type of the `Picture` field is `*string`, so if I make it nil it just gets omitted from the request body

### Expectation

I expect to be able to remove the User picture with the SDK, by either setting it to an empty string
```go
func TestRemoveUserProfilePicture(t *testing.T) {
	userId := "USER_ID"

	emptyString := ""
	userUpdate := &management.User{
		Picture: &emptyString,
	}
	err := client.User.Update(context.Background(), userId, userUpdate)

	assert.NoError(t, err)
	assert.Equal(t, userUpdate.GetPicture(), "")
}
```

Or that the type of Picture is `sql.NullString` (or similar) and I can explicitly set it to null:
```go
func TestRemoveUserProfilePicture(t *testing.T) {
	userId := "USER_ID"

	nullString := sql.NullString{}
	userUpdate := &management.User{
		Picture: &nullString,
	}
	err := client.User.Update(context.Background(), userId, userUpdate)

	assert.NoError(t, err)
	assert.Equal(t, userUpdate.GetPicture(), "")
}
```

### Reproduction

1. Create a user with a profile picture
2. Try to remove the profile picture using the SDK
3. It doesn't work

### Auth0 Go SDK version

1.0.1

**Comment by ewanharris** [comment]
Hey @JakubC-projects thanks for the issue! This is a difficult one to solve in the SDK currently as the structs are shared between create and update requests and whilst the update API accepts these values the create one doesn't.

What I would recommend is following something similar to the custom user struct example [here](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#providing-a-custom-user-struct), but to not embed the `management.User` struct as that would override the `picture` tag. That could then be combined with the `api.Request` function when you know you want to update the picture to be null.

```go
type CustomUser struct {
	Picture *string `json:"picture"`
}

err = api.Request(context.Background(), http.MethodPatch, api.URI("users", userID), &CustomUser{
	Picture: nil,
})

if err != nil {
	log.Fatalf("failed to update %+v", err)
}
```

Alternatively, you could use the `user_metadata` as described in [this document](https://auth0.com/docs/manage-users/user-accounts/change-user-picture).

**Comment by JakubC-projects** [comment]
Thanks for the answer @ewanharris,
We ended up using a custom struct to do those user updates
