### ISSUE TITLE
LogWrapper fails to unmarshal log user_id field

### ISSUE THREAD

**Issue by tfadeyi** [auth0/go-auth0#303]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I've implemented a Prometheus exporter,https://github.com/tfadeyi/auth0-simple-exporter, that uses the go-auth0 library to export tenant log events to prometheus, recently one of the users as reported the following error

```
json: cannot unmarshal number into Go struct field logWrapper.user_id of type string"
```

Following the call stack, the exporter makes a request to go-auth0 log client to fetch logs, but the operation seems to fail and an error seems to occur during the unmarshalling of the log struct by the library https://github.com/auth0/go-auth0/blob/main/management/log.go#L162.

The user is using a custom database connection but I don't know if it's possible for it to have made it possible to have a number instead of a string. Looking at the auth0 docs the log `user_id` seems to never be a number and always string. 
I'm not 100% sure if it's possible that a log entry ended with number instead of a string for the `user_id` field.

### Expectation

No unmarshalling error occurs when listing logs.

### Reproduction

I was only able to reproduce it in the unit tests for the log client.
If a log element has `user_id` as a number instead of string the error will occur.

```json
{
 "log_id": "..."
 "user_id": 1
}
```

### Auth0 Go SDK version

1.1.0

**Comment by congzhegao** [comment]
Having the same issue with `logWrapper.connection`
```
failed to unmarshal response payload: json: cannot unmarshal array into Go struct field logWrapper.connection of type string
```

**Comment by ewanharris** [comment]
@tfadeyi I think unfortunately we'd classify this as an issue on the connection side as it's expected for `user_id` [to be a string](https://auth0.com/docs/api/management/v2/logs/get-logs-by-id#:~:text=event%20applies%20to.-,user_id,-string) not a number.

@congzhegao I think that error [would be similar](https://auth0.com/docs/api/management/v2/logs/get-logs-by-id#:~:text=of%20this%20event.-,connection,-string), when you view the log is there just a single connection name in that array?

**Comment by tfadeyi** [comment]
Hi @ewanharris thank you for looking into it, is there anything that can be done to prevent or mitigate the issue?

**Comment by hobbsh** [comment]
@ewanharris Does this apply to a numerical string? I am unfortunately not seeing anything on our end that is indicating that `user_id` is anything but a string so I'm a bit lost. Is there anything that can be checked in the logs themselves and the connection to validate the behavior?

**Comment by ewanharris** [comment]
@tfadeyi I think on the consumer of go-auth0 side there isn't much that can be done other than handling and logging the error

@hobbsh, from what we've seen in the past I think that could be it, I'm not sure if it's potentially something where it's been unintentionally converted while the log entry was created

**Comment by tfadeyi** [comment]
Thank you @ewanharris, I'll close the issue. Thank you for taking a look at this
