### ISSUE TITLE
docs do not explain how to paginate

### ISSUE THREAD

**Issue by DavidS-om** [auth0/go-auth0#305]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The documentation does not explain how to use pagination.

PS: bonus bug: the link in the PR template to the Auth0 Community forums (`https://community.auth0.com/c/sdks/5`) 404s

### Expectation

A concise explanation of pagination using the go-auth0 sdk, including
* a code snippet showing how to do it
* a discussion of whether sorting is needed or not
* explanation of tradeoffs using `List.Next` vs page indexes
* links from each method returning a `List` to the explanation

### Reproduction

Infinite loop doing the naive thing:
```
auth0API, _ := management.New(...)
ul, _ := auth0API.User.List(ctx)
for {
	for _, u := range ul.Users {
		// process user
	}

	if !ul.HasNext() {
		break
	}
	ul, _ = auth0API.User.List(ctx, management.From(ul.Next))
}
```

### Auth0 Go SDK version

v1.2.0

**Comment by ewanharris** [comment]
Hey @DavidS-om, thanks for the issue!

We have an example of performing page and checkpoint based pagination in our [examples file](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#pagination).

Do you think if we moved this to the [doc.go](https://github.com/auth0/go-auth0/blob/main/doc.go) file (so that it would be included in the packages godoc) it would be easier to find?

**Comment by DavidS-om** [comment]
> Hey @DavidS-om, thanks for the issue!
> 
> We have an example of performing page and checkpoint based pagination in our [examples file](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#pagination).
> 
> Do you think if we moved this to the [doc.go](https://github.com/auth0/go-auth0/blob/main/doc.go) file (so that it would be included in the packages godoc) it would be easier to find?

absolutely. I'm seeing this file the first time now. And - except for my weak copy/paste game - it worked fine first try!

**Comment by ewanharris** [comment]
To round this out, we now have pagination examples in [the godoc](https://pkg.go.dev/github.com/auth0/go-auth0/management).

Thanks for raising this @DavidS-om!
