### ISSUE TITLE
make authenticationError an exported type

### ISSUE THREAD

**Issue by magaldima** [auth0/go-auth0#315]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The `authenticationError` is not an exported type even though it has JSON annotations. 

I would like to be able to handle specific authentication errors in my code and I can't because this type is not exported from the package.

For example, how can I condition on an `mfa_required` error from the `LoginWithPassword` function?

### Describe the ideal solution

Export the `AuthenticationError` type.

### Additional context

https://go.dev/blog/error-handling-and-go

**Comment by ewanharris** [comment]
Thanks for the issue @magaldima, this was an oversight when implementing the auth client so we'll expose an error that allows working with the returned errors more easily

**Comment by ewanharris** [comment]
Thanks again for the issue @magaldima, this is now part of the v1.4.0 release and we also included some docs [here](https://pkg.go.dev/github.com/auth0/go-auth0/authentication#hdr-Handling_Errors)
