### ISSUE TITLE
Support MFA APIs

### ISSUE THREAD

**Issue by magaldima** [auth0/go-auth0#316]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The current SDK contains only a portion of the Auth0 Authentication APIs. It's missing MFA APIs.

### Describe the ideal solution

Add support for MFA and the rest of APIs as described in the Auth0 Authentication APIs: https://auth0.com/docs/api/authentication

**Comment by ewanharris** [comment]
Thanks for the request @magaldima, just to confirm would you be looking for the authenticators endpoints too or would the existing authenticators APIs in the management SDK suffice for you?

**Comment by ewanharris** [comment]
Thanks again for the issue @magaldima, we released this yesterday in v1.4.0 of the SDK and you can find the docs [here](https://pkg.go.dev/github.com/auth0/go-auth0/authentication#MFA). We chose to not add the authenticators endpoint but instead recommend usage of the management API
