### ISSUE TITLE
Error parsing does not support `mfa_token` field when the error is a 403 `mfa_required` error

### ISSUE THREAD

**Issue by rmberg** [auth0/go-auth0#351]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am attempting to implement a backend call to `OAuth.LoginWithPassword` and when the error returned is an MFA required error, I don't have the ability to access the `mfa_token` returned in the error response.  This is needed so that I can trigger the MFA challenge flow properly.

### Expectation

The `Error` struct should support an `MFAToken` field

### Reproduction

1. Given a call to `LoginWithPassword` for a user that has MFA enabled
2. an error is returned with status code 403 and error code `mfa_required`
3. there is not a way to retrieve the `mfa_token` from the error response

### Auth0 Go SDK version

v1.4.0

**Comment by developerkunal** [comment]
Hi @rmberg,

Apologies for the delay in getting back to you!

I've updated the tag to **feature** since it wasn't a bug. We previously did not have support for `MFA_TOKEN` in our SDK, but we have just released a new version that includes this functionality.

You can now retrieve the `MFA_TOKEN` like this:

```go
func main() {
	// Load environment variables from a .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	// Initialize an Auth0 authentication client
	auth, err := authentication.New(
		context.Background(),
		os.Getenv("AUTH0_DOMAIN"),
		authentication.WithClientID(os.Getenv("AUTH0_CLIENT_ID")),
		authentication.WithClientSecret(os.Getenv("AUTH0_CLIENT_SECRET")),
	)
	if err != nil {
		log.Fatalf("Failed to initialize Auth0 client: %+v", err)
	}

	// Perform OAuth login with username and password
	a, err := auth.OAuth.LoginWithPassword(context.Background(), oauth.LoginWithPasswordRequest{
		Audience: "https://your-auth0-domain/api/v2/",
		Username: "user@example.com",    // Replace with actual username
		Password: "password",            // Replace with actual password
	}, oauth.IDTokenValidationOptions{})

	// Handle MFA and authentication-specific errors
	var authErr *authentication.Error
	if errors.As(err, &authErr) {
		log.Println("MFA Token (if available):", authErr.GetMFAToken())
		log.Println("Error ID:", authErr.Error())
		return
	}

	// Success! Access token is available
	log.Printf("Login successful! Access token: %s", a.AccessToken)
}
```

Please let me know if you need any further assistance!

**Comment by developerkunal** [comment]
Hi @rmberg ,

Closing this feature request, if required please open another issue or reopen this.
