### ISSUE TITLE
Body being sent in get requests

### ISSUE THREAD

**Issue by fernandes6502** [auth0/go-auth0#358]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to Read a specific client by the ClientID in our go backend, it works when I try via postman but fail when I perform the same call in the go sdk. I enabled the debug log and saw that the Auth0 Client is sending "null" as body in the GET request and our Firewall policy is blocking it.

```go
a0Client, err := q.mgmtAPIClient.Client.Read(ctx, clientID)
```

debug log:
```
\nGET /api/v2/clients/aaaaaaaa HTTP/1.1\r\nHost: my-domain.com\r\nUser-Agent: Go-Auth0/1.4.0\r\nContent-Length: 5\r\nAuth0-Client: HIDDEN\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\nnull\n
```

### Expectation

it should return the client

### Reproduction

1. Create a small go lang application that will try to fetch a client.
2. use the __Read__ method from the management SDK and activate the debug log.
3. Within the debug log, it's possible to see the auth0 sending the "null" in the request even if it is a GET.

### Auth0 Go SDK version

1.4.0

**Comment by developerkunal** [comment]
Hi @fernandes6502 ,

Great news! The issue has been fixed in version 1.5.0. Please take a moment to review, and feel free to reach out if you encounter any further issues.
