### ISSUE TITLE
Support enabled_connections field in the CreateOrganization call

### ISSUE THREAD

**Issue by alenkacz** [auth0/go-auth0#366]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

there's no possibility to pass in enabled connection to create organization call even though API supports it https://auth0.com/docs/api/management/v2/organizations/post-organizations

### Describe the ideal solution

https://github.com/auth0/go-auth0/blob/main/management/organization.go#L10 organization will allow to specify these connections

### Alternatives and current workarounds

alternative is to make an extra calls to auth0 api to add the connections but we're trying to limit the calls to auth0 because of the rate limits imposed

**Comment by developerkunal** [comment]
Hi @alenkacz ,

The feature you requested has been released in version 1.6.0. Please take a look and let us know if you encounter any issues.
