### ISSUE TITLE
Missing delete refresh tokens from a user

### ISSUE THREAD

**Issue by emmaLP** [auth0/go-auth0#380]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In the management API users sections, there is an API endpoint for revoking refresh tokens for a user
https://auth0.com/docs/api/management/v2/users/delete-refresh-tokens-for-user

This functionality is not exposed in the SDK

We have a required during GDPR deletion to revoke a user's refresh tokens and block the user, before proceeding to delete the user. This is to prevent a user from having a validate access token and the ability to exchange a refresh token for an access token once they have requested a deletion

### Describe the ideal solution

Add functionality to the SDK to be able to call this api: https://auth0.com/docs/api/management/v2/users/delete-refresh-tokens-for-user

### Alternatives and current workarounds

If this is not implemented, we would need to call the API direct rather than having the SDK manage authentication etc on our behalf.

**Comment by developerkunal** [comment]
Hi @emmaLP  ,

The feature you requested has been released in version 1.6.0. Please take a look and let us know if you encounter any issues.
