### ISSUE TITLE
Support for MFA Management API

### ISSUE THREAD

**Issue by jaskerv** [auth0/go-auth0#409]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Its nice to see that we support some mfa functions but it would be good to have a SDK function to manage MFA such as retrieve, enrol, remove etc

### Describe the ideal solution

Have feature parity with mfa management api endpoints.

**Comment by developerkunal** [comment]
Hi @jaskerv,

Apologies for the delay in getting back to you!

We have just released a new version of the SDK that adds support for these endpoints in the Authentication module. You can now list, enroll, or remove authenticators using the SDK.

Could you please confirm if this was the feature you were requesting, or if it’s related to the Management APIs?

**Comment by developerkunal** [comment]
Hi @jaskerv,

We're closing this feature request as it has already been released. If needed, feel free to open a new issue or reopen this one.
