### ISSUE TITLE
LoginWithClientCredentials should support scopes to match oauth spec

### ISSUE THREAD

**Issue by bredelman** [auth0/go-auth0#436]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I assumed that [LoginWithClientCredentials](https://github.com/auth0/go-auth0/blob/main/authentication/oauth.go#L142C17-L142C43) supported scope but looking at the types, it appears that it does not. According to the [spec](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2) it is optional for client credentials and is something supported by the auth0 api in general.

### Describe the ideal solution

Ideally LoginWithCredentials would support scope 

### Alternatives and current workarounds

I can just do an http post 🤷

**Comment by developerkunal** [comment]
Hi @bredelman,

Sorry for the delay in replying.

Regarding your question about `LoginWithClientCredentials`, you can use the `ExtraParameters` field in the `LoginWithClientCredentialsRequest` struct to add additional URL parameters, such as the scope.

For example:

```go
authAPI, err := authentication.New(
    context.TODO(), // Replace with a Context that better suits your usage
    domain,
    authentication.WithClientID(clientID),
    authentication.WithClientSecret(clientSecret), // Optional depending on the grants used
)
if err != nil {
    log.Fatalf("failed to initialize the auth0 authentication API client: %+v", err)
}

tokenSet, err := authAPI.OAuth.LoginWithClientCredentials(context.Background(), oauth.LoginWithClientCredentialsRequest{
    ExtraParameters: map[string]string{
        "scope": "", // This sets the scope as a URL parameter
        // Add other additional parameters here
    },
}, oauth.IDTokenValidationOptions{})
if err != nil {
    log.Fatalf("failed to retrieve tokens: %+v", err)
}
```

This approach correctly sets the `scope` as a key-value pair in the `ExtraParameters` map, which will be included in the request as an additional URL parameter.

**Comment by bredelman** [comment]
Ah thanks, I guess I missed that the first time around.
