### ISSUE TITLE
Function to enable WebAuthN Platform factor updates wrong factor

### ISSUE THREAD

**Issue by brianhyder** [auth0/go-auth0#46]
While looking at the new Terraform module, I saw that webauthn support did not appear in the Guardian resource.  I dug in to the source code for the Go SDK and looked at the implementation for enabling webauthn.  The [function](https://github.com/auth0/go-auth0/blame/main/management/guardian.go#L376) appears to pass in `webauthn-roaming` as the factor type when it should be passing `webauthn-platform`.  

Looking at the [unit test](https://github.com/auth0/go-auth0/blob/main/management/guardian_test.go#L218), it appears that it only verifies the `enabled` property and not the factor type that was also provided.

**Comment by sergiughf** [comment]
Hey @brianhyder! Thanks a lot for spotting this, we'll fix this soon! Much appreciated.

**Comment by sergiughf** [comment]
This was now fixed and the tests improved. Thanks again @brianhyder! 🙏🏻 

We'll include this in the next release.
