### ISSUE TITLE
Unable to set token_endpoint_auth_method to null

### ISSUE THREAD

**Issue by jbaldwinroberts** [auth0/go-auth0#474]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to configure my application to use `private_key_jwt` authentication in `ClientAuthenticationMethods`. For this I need to set `TokenEndpointAuthMethod` to null, however the SDK does not allow for null values to be set due to:

```
// Defines the requested authentication method for the token endpoint.
// Possible values are:
// 	'none' (public client without a client secret),
// 	'client_secret_post' (client uses HTTP POST parameters) or
// 	'client_secret_basic' (client uses HTTP Basic)
TokenEndpointAuthMethod *string `json:"token_endpoint_auth_method,omitempty"`
```

This prevents clients from switching to the `private_key_jwt` authentication method as the following error is returned:
`400 Bad Request: `token_endpoint_auth_method` must be disabled (set to null) when migrating to `client_authentication_methods`.`

This is the same issue as [this](https://github.com/auth0/auth0-java/issues/642) one in the java SK.

### Expectation

I should be able to configure my application to use `private_key_jwt` authentication.

### Reproduction

- Have a Machine to Machine client with client secret (token_endpoint_auth_method=client_secret_post)
- Create a credential
- Add the credential to the client via the SDK, using the update client method, while setting token_endpoint_auth_method=null
- Observe error message: "token_endpoint_auth_method must be disabled (set to null) when migrating to client_authentication_methods."

### Auth0 Go SDK version

v1.13.0

**Comment by developerkunal** [comment]
Hi @jbaldwinroberts,

Hope you're doing well!

Currently, the SDK doesn’t directly support nullable variables, but we’ve been using the approach mentioned in this example: [Providing a Custom User Struct](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#providing-a-custom-user-struct). This involves creating a custom request as a workaround.

That said, we’re planning to add support for nullable values in V2, which should address this limitation.

Let me know if you have any questions!

**Comment by jbaldwinroberts** [comment]
great that solves the issue, thanks for the quick reply
