### ISSUE TITLE
Prompt.SetCustomText not passing body

### ISSUE THREAD

**Issue by arcticShadow** [auth0/go-auth0#58]
### Describe the problem

I Think i may have discovered a bug - the SetCustomText method does not appear to be passing a body. 

However, I have never written a line of Go before today, so it very possible i have done something wrong. 

Originally discovered by using the terraform provider for setting prompt language texts - and noticing that the body of the request is empty, in auth0 logs. 

Tracked the code backwards the the go sdk, and have produced the following test script.  

```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/auth0/go-auth0/management"
)

func main() {
	m, err := management.New("CLIENT_DOMAIN", management.WithClientCredentials("CLIENT_ID", "CLIENT_SECRET"))
	if err != nil {
		// handle err
	}

	var body map[string]interface{}
	err1 := json.Unmarshal([]byte(`{ "login": { "title": "Welcome" } }`), &body)
	if err1 != nil {
		fmt.Println(err)
	}

	err = m.Client.Prompt.SetCustomText("login", "en", body)
	if err != nil {
		fmt.Printf("Something broken")
		fmt.Println(err)

	}

}

```

When i run the code above, I get no output (indicating success) however, the logs in auth0 show no body was passed. (same issue as i encountered with the terraform provider) 

Could someone help to identify if this is an issue, or if i am using this incorrectly?

### What was the expected behavior?

I expect 
```go
	var body map[string]interface{}
	err1 := json.Unmarshal([]byte(`{ "login": { "title": "Welcome" } }`), &body)
	if err1 != nil {
		fmt.Println(err)
	}

	err = m.Client.Prompt.SetCustomText("login", "en", body)
```
To make a PUT request to Auth0 Management API, and the language strings are included in the body of the request when viewing the auth0 logs.

### Reproduction

Reproduction steps included above :-) 

### Environment
Im not sure how to validate what version of things i am using - i have never written GO before today. 

The go.mod file in my test directory has the following content (this is automatically generated - the only dependency i added with `go get` was `github.com/auth0/go-auth0` :
```
module sdk-test

go 1.18

require (
	github.com/PuerkitoBio/rehttp v1.1.0 // indirect
	github.com/auth0/go-auth0 v0.6.3 // indirect
	github.com/golang/protobuf v1.4.2 // indirect
	golang.org/x/net v0.0.0-20210510120150-4163338589ed // indirect
	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 // indirect
	google.golang.org/appengine v1.6.6 // indirect
	google.golang.org/protobuf v1.25.0 // indirect
)
```

Any other info i can provide, please let me know.

**Comment by sergiughf** [comment]
Hey @arcticShadow thanks for opening this issue. Apologies for the delay in answering your inquiry. 

A couple of things:

- You don't necessarily need to unmarshal the payload as as string and then pass it back to the `SetCustomText` call, you can simply do:

```go
body := map[string]interface{}{
    "login": map[string]interface{}{
	"title": "Welcome",
    },
}

err := m.Prompt.SetCustomText(prompt, lang, body)
```

> When i run the code above, I get no output (indicating success) however, the logs in auth0 show no body was passed. (same issue as i encountered with the terraform provider)

If something goes wrong, you're gonna get back an error on the `SetCustomText` call, so you should always check that, e.g.:

```go
err := m.Prompt.SetCustomText(prompt, lang, body)
if err != nil {
 // handle err
}
```

If there's no error you can safely assume the call was successful and the prompt got updated. 

The Logs won't show you the body that will get passed in this case unfortunately, but you can check that the prompt and language got updated successfully by using the API Explorer: https://auth0.com/docs/api/management/v2#!/Prompts/get_custom_text_by_language. 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/28300158/172586654-ad62fc94-10b5-4221-be33-7073dcccb45b.png">

Let me know if this helps. Appreciate your patience 🙏🏻

**Comment by arcticShadow** [comment]
Thanks for the response, 

I'll check out the suggestion tomorrow and see if I progress. However, I discovered this through the terraform provider not functioning as expected - if the unmarshalling is not required, does that mean that the terraform provider is wrong?

https://github.com/auth0/terraform-provider-auth0/blob/main/auth0/resource_auth0_prompt_custom_text.go#L120

I'm not at a computer today, so will check this out more tomorrow.


Thanks

**Comment by sergiughf** [comment]
Hey @arcticShadow, the unmarshalling in the terraform provider is required as we're fetching the values from the terraform state as a string and we need to convert it to the proper struct before sending it to the API. We weren't able to reproduce any issues managing custom text through the provider, as such we'll be closing this issue but feel free to reopen in case of need or if we can clarify anything else further.
