### ISSUE TITLE
Absence of `multifactor` field in `User` struct

### ISSUE THREAD

**Issue by IvanProdaiko94** [auth0/go-auth0#77]
### Describe the problem you'd like to have solved.
I'm always frustrated when I'm trying to get user and deal with `Multifactor []string` property, but there is no such property in the library. This field is actually a part of the api. I do not understand why it's missing in the lib(((

### Describe the ideal solution.
Add `multifactor` field to `User` struct

**Comment by sergiughf** [comment]
Hey @IvanProdaiko94 thanks for reporting this, we'll look into adding support for this soon.

**Comment by sergiught** [comment]
Hey @IvanProdaiko94 this is now available with https://github.com/auth0/go-auth0/releases/tag/v0.9.3. 👋🏻
