### ISSUE TITLE
Suggested Way to Check StatusCode of Management API Errors

### ISSUE THREAD

**Issue by mattmelgard** [auth0/go-auth0#79]
### Describe the problem

This may just be my misunderstanding of how this library is meant to be used, but with [`managementError`](https://github.com/auth0/go-auth0/blob/main/management/management.go#L348) being private to the package, I don't see an elegant or idiomatic way to retrieve the status code of an error from the management API.

If my understanding is correct, you should be able to use [`errors.As()`](https://pkg.go.dev/errors#As) to recursively unwrap and find an error that matches the target type, but because `management.managementError` is not exposed on the package, and [`management.Error`](https://github.com/auth0/go-auth0/blob/main/management/management.go#L341) is an interface, I don't see a clean way to get at and check the status code of the error that is agnostic to the error type being returned.

### What was the expected behavior?

I need some way to check if the status code of an error returned from the auth0 management API in an idiomatic manner. Right now this only seems to be possible if I manually unwrap the error and then type assert it as a `management.Error` but that seems kind of non-standard to me. I am less experienced in Golang than other languages though, so it is possible that there is a pattern/understanding I'm missing here. Please LMK if so.

### Reproduction

Not sure what all to provide here, but I can offer snippets of the code if needed. The core issue isn't really something "reproduce-able" per-se but more just a question of implementation/approach.

### Environment

- Version of `go-auth0` used: `gopkg.in/auth0.v5/management`
- Other modules/plugins/libraries that might be involved: N/a

**Comment by mattmelgard** [comment]
Ah, well, I do seem to have found a way to do this actually, my bad. I must not have been passing `management.Error` to `errors.As` correctly. The following approach seems to work:

```
package main

import (
...
	"gopkg.in/auth0.v5/management"
)

func checkError(logger *logger.Logger, err error) {
	if err == nil {
		return
	}
	var managementErr management.Error

	if errors.As(err, &managementErr) {
		switch managementErr.Status() {
		case 409, 404:
			return
		default:
			logger.WithError(err).Panic("")
		}
	}
	logger.WithError(err).Panic("")
}
```

Sorry for the false alarm!

**Comment by sergiughf** [comment]
Glad you were able to solve this @mattmelgard! 🥳 Please don't hesitate to reach out in case of any other questions.
