### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by zeromberto** [auth0/go-auth0#8]
Hey ho,

are there any plans to provide a client for the [Authentication API](https://auth0.com/docs/api/authentication)?

**Comment by sergiughf** [comment]
Hey @zeromberto, thanks for your question. 

As of now we do not have any plans to provide a client for the authentication API.

For now I would recommend taking a look at how we authenticate against Auth0 within our golang web-app sample: https://github.com/auth0-samples/auth0-golang-web-app/blob/master/01-Login/platform/authenticator/auth.go#L9 that uses the `golang.org/x/oauth2` pkg for it. Feedback on that is highly appreciated. 

Quickstart Docs: https://auth0.com/docs/quickstart/webapp/golang

Let me know if you have any other questions.

**Comment by zeromberto** [comment]
Hey @sergiughf,

thanks for your update. I'm aware of `golang.org/x/oauth2` but my use case is a little different. I'd like to trigger the password reset flow from a golang client. So I need to issue a request to the `/dbconnections/change_password` endpoint. I don't want to use the `tickets` from the management API because a want to I'd like to reuse the email dispatch.

What is your opinion on this matter? Am I trying to implement some bad?

**Comment by sergiughf** [comment]
Hey @zeromberto, apologies for the late reply. I somehow missed this. 

For your use case we have a Go code sample available at https://auth0.com/docs/authenticate/database-connections/password-change#authentication-api. Would this help?

**Comment by zeromberto** [comment]
Yes, thank you!
